/**
 * 真实数据库：列级补丁（`ts-grm-patches` 的 autoIncrement / default）往返。
 *
 * 断言链条：`applyPatches()` + 真实 model(...) → createSchema → 适配器 →
 * Postgres 建表 SQL → 执行 → introspect → **diff 为空**。
 *
 * 为什么必须连真库：PostgreSQL 的 identity 与默认值在 catalog 里会以另一种
 * 写法出现（`generated by default as identity` → attidentity；字面量默认值会被
 * 补上 `::character varying` 之类的 cast），只有真实 introspect 才能证明
 * 「模型声明 → DDL → 读回」三者对齐。无 PG_HOST 时整体跳过。
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { lookup } from 'node:dns/promises';
import { Pool, type PoolClient } from 'pg';
import { applyPatches } from 'ts-grm-patches';
import {
  EntityManager,
  createSchema,
  dsl,
  model,
  newSqlClient,
  PostgresDriver,
  prop,
} from '../src/vendor/ts-grm';
import { tableDefsToSchema } from '../src/schema/adapter';
import { SchemaDiffer } from '../src/differ';
import { PostgresDdlGenerator } from '../src/ddl/postgres';
import { PostgresIntrospector } from '../src/introspector/postgres';
import type { SqlQueryable } from '../src';
import type { SqlClientImplementor } from '../src/vendor/ts-grm';
import type { Schema } from '../src/schema/model';

const PG_HOST = process.env.PG_HOST;
const PG_CONFIG = {
  host: PG_HOST ?? '',
  port: Number(process.env.PG_PORT ?? 5432),
  database: process.env.PG_DATABASE ?? 'ts_grm_migrate_test',
  user: process.env.PG_USER ?? 'postgres',
  password: process.env.PG_PASSWORD ?? '',
};

/** 集成测试专用 schema，避免污染 public */
const TEST_SCHEMA = 'ts_grm_migrate_patch';

const describePg = PG_HOST != null ? describe.sequential : describe.skip;

// 补丁必须在任何 model(...) 定义之前安装
applyPatches();

const ITEM = model(
  'PatchItem',
  'id',
  class {
    id = prop.i32().autoIncrement();
    status = prop.str(20).default('active');
    createdAt = prop.dt().default(dsl.native.date`now()`);
  },
);

const NOTE = model(
  'PatchNote',
  'id',
  class {
    id = prop.i32();
    body = prop.text().default('empty');
  },
);

describePg('列级补丁（真实 PostgreSQL）', () => {
  let pool: Pool;

  beforeAll(async () => {
    try {
      const { address } = await lookup(PG_HOST ?? '');
      PG_CONFIG.host = address;
    } catch {
      // 解析失败就保留域名，让连接错误自然暴露
    }
    pool = new Pool({ ...PG_CONFIG, max: 2 });
  });

  afterAll(async () => {
    await pool?.query(`drop schema if exists "${TEST_SCHEMA}" cascade`).catch(() => undefined);
    await pool?.end();
  });

  /** 目标态：真实模型链路（不连库，createSchema 只做元数据计算） */
  function targetSchema(): Promise<Schema> {
    const sqlClient = newSqlClient(new PostgresDriver(pool as never), {
      entityManager: EntityManager.combine(ITEM as never, NOTE as never),
    }) as unknown as SqlClientImplementor;
    return createSchema(sqlClient as never).then((defs) =>
      tableDefsToSchema(defs, sqlClient.driver, { dialect: 'postgres' }),
    );
  }

  /** 在干净 schema 里跑（search_path 指向它，DDL 不带 schema 前缀也能落对位置） */
  async function inFreshSchema<T>(fn: (client: PoolClient) => Promise<T>): Promise<T> {
    const client = await pool.connect();
    try {
      await client.query(`drop schema if exists "${TEST_SCHEMA}" cascade`);
      await client.query(`create schema "${TEST_SCHEMA}"`);
      await client.query(`set search_path to "${TEST_SCHEMA}"`);
      return await fn(client);
    } finally {
      await client.query(`drop schema if exists "${TEST_SCHEMA}" cascade`).catch(() => undefined);
      client.release();
    }
  }

  it('identity 列与默认值建表后 introspect 与模型等价（diff 为空）', async () => {
    await inFreshSchema(async (client) => {
      const target = await targetSchema();
      const from: Schema = { tables: [] };
      const diff = new SchemaDiffer().diff(from, target);
      const statements = new PostgresDdlGenerator().statements(diff);
      for (const sql of statements) {
        await client.query(sql);
      }

      // 自增与默认值真的生效（不只是元数据好看）
      await client.query(`insert into "patch_item" default values`);
      const inserted = await client.query(`select "id", "status", "created_at" from "patch_item"`);
      expect(inserted.rows[0]).toMatchObject({ id: 1, status: 'active' });
      expect(inserted.rows[0]?.created_at).not.toBeNull();

      const actual = await new PostgresIntrospector({
        query: client as unknown as SqlQueryable,
        schema: TEST_SCHEMA,
      }).introspect();

      const item = actual.tables.find((t) => t.name === 'patch_item');
      expect(item).toBeDefined();
      expect(item?.columns.find((c) => c.name === 'id')?.autoIncrement).toBe(true);

      // 最强断言：catalog 的 identity/默认值写法与目标态对齐时，diff 必须为空
      expect(new SchemaDiffer().diff(actual, target).changes).toEqual([]);
    });
  }, 60_000);

  it('去掉默认值声明 → 生成 drop default（模型是权威）', async () => {
    await inFreshSchema(async (client) => {
      // 先按「有默认值」建好，再用一个没有默认值的同构目标态去 diff
      const withDefault = await targetSchema();
      for (const sql of new PostgresDdlGenerator().createStatements(withDefault)) {
        await client.query(sql);
      }
      const target = await targetSchema();
      const withoutDefault: Schema = {
        tables: target.tables.map((t) => ({
          ...t,
          columns: t.columns.map((c) => (c.name === 'status' ? { ...c, default: '' } : c)),
        })),
      };
      const actual = await new PostgresIntrospector({
        query: client as unknown as SqlQueryable,
        schema: TEST_SCHEMA,
      }).introspect();
      const diff = new SchemaDiffer().diff(actual, withoutDefault);
      const statements = new PostgresDdlGenerator().statements(diff);
      expect(statements.some((s) => s.includes('alter column "status" drop default'))).toBe(true);
    });
  }, 60_000);
});
