import { diagnostic } from "./diagnostics/error.js";
/**
 * DDL 生成器 —— 把语义层的 diff 操作集翻译成方言 SQL。
 *
 * 对应 prisma-engines 的 `libs/sql-ddl`（语句构造）+ `sql_renderer.rs`（方言分发）。
 * 每个方言一个实现（Postgres / SQLite 见 src/ddl/）。
 *
 * SQLite 的普通建表可复用 ts-grm 原生；默认值与自增由自建 DDL 表达。
 * 列级变更由各方言生成；SQLite 需要重建表的变更明确拒绝。
 */
import type { Diff } from "./diff/types.js";
import type {
  Column,
  Constraint,
  Index,
  OnDelete,
  Schema,
  Table as SchemaTable,
} from "./schema/model.js";
import type { SchemaDriver } from "./schema/adapter.js";
import type { TableDef } from "./vendor/ts-grm.js";
import type { Dialect } from "./introspector.js";

/** Both states from the same introspection/diff pass, needed by whole-column DDL. */
export interface DdlContext {
  readonly from: Schema;
  readonly to: Schema;
}

export interface DdlGenerator {
  readonly dialect: Dialect;

  /** 把 diff 渲染为按序执行的 SQL 语句数组 */
  statements(diff: Diff, context?: DdlContext): ReadonlyArray<string>;

  /**
   * 把整个 schema 渲染为建表 SQL（用于空库初始化）。
   * 传入目标态 TableDef 映射时逐表复用 ts-grm 原生 toCreationStatements。
   */
  createStatements(schema: Schema): ReadonlyArray<string>;
}

/** DDL 生成器构造选项（目前仅 SQLite 需要：重建表/建表复用 ts-grm 原生） */
export interface DdlGeneratorOptions {
  /** 方言类型映射（原生 toCreationStatements 需要；提供 tableDefs 时必填） */
  driver?: SchemaDriver;
  /** 表名 → 原生 TableDef（目标态模型产物；CREATE_TABLE / 重建表时条件复用原生） */
  tableDefs?: ReadonlyMap<string, TableDef>;
}

// ---- 共享工具 --------------------------------------------------------------

/** 标识符加引号（方言无关的通用形式；表名/列名来自数据库实际名字，加引号防保留字/大小写折叠） */
export function quoteIdentifier(name: string): string {
  return `"${name.replaceAll('"', '""')}"`;
}

/** 列定义片段：`"NAME" type [identity] [null|not null] [default ...]` */
export function columnSql(column: Column, dialect: Dialect): string {
  const identity =
    column.autoIncrement && dialect === "postgres" ? " generated by default as identity" : "";
  const defaultValue =
    column.default !== undefined && column.default !== "" ? ` default ${column.default}` : "";
  return `${quoteIdentifier(column.name)} ${column.type}${identity}${
    column.nullable ? " null" : " not null"
  }${defaultValue}`;
}

/** ON DELETE 动作 → SQL 子句（空串 = 省略，方言默认行为） */
export function onDeleteSql(onDelete: OnDelete): string {
  switch (onDelete) {
    case "CASCADE":
      return " on delete cascade";
    case "SET_NULL":
      return " on delete set null";
    case "SET_DEFAULT":
      return " on delete set default";
    case "RESTRICT":
      return " on delete restrict";
    case "NO_ACTION":
      return "";
  }
}

/** 约束名：显式名字优先，否则按表/种类确定性生成（diff 内容匹配，名字只用于 DDL） */
export function constraintName(table: string, constraint: Constraint, seq: number): string {
  if (constraint.name != null) {
    return constraint.name;
  }
  switch (constraint.kind) {
    case "PRIMARY_KEY":
      return `${table}_pk`;
    case "UNIQUE":
      return `${table}_uq_${constraint.columns.join("_")}`;
    case "FOREIGN_KEY":
      return `${table}_fk_${constraint.columns.join("_")}`;
    case "CHECK":
      return `${table}_ck_${seq}`;
  }
}

/**
 * 从零生成建表 SQL（自建兜底；提供 TableDef 映射时由方言实现改走 ts-grm 原生）。
 * 约束全部 inline（PG / SQLite 都支持表级约束），语义与 ts-grm toCreationStatements 等价。
 *
 * 列级 `default` / `autoIncrement` 在此渲染：
 * - PostgreSQL：自增用 `generated by default as identity`（identity 列不能有 default）；
 * - SQLite：`AUTOINCREMENT` 只能写在 `INTEGER PRIMARY KEY` 上，因此该列内联主键、
 *   并跳过后面的表级主键约束（见 `sqliteAutoIncrementColumn`）；
 * - 其他方言的建表 SQL 由各自的 DDL 实现负责（src/ddl/mysql.ts、src/server/ddl.ts）。
 */
export function createTableSql(table: SchemaTable, dialect: Dialect): string {
  const sqliteAuto = dialect === "sqlite" ? sqliteAutoIncrementColumn(table) : undefined;
  const parts: Array<string> = [];
  for (const column of table.columns) {
    if (column === sqliteAuto) {
      // SQLite：`INTEGER PRIMARY KEY AUTOINCREMENT` 是列约束，不能同时再有表级主键
      parts.push(`  ${quoteIdentifier(column.name)} integer not null primary key autoincrement`);
      continue;
    }
    parts.push(`  ${columnSql(column, dialect)}`);
  }
  let seq = 0;
  for (const constraint of table.constraints) {
    if (
      sqliteAuto != null &&
      constraint.kind === "PRIMARY_KEY" &&
      constraint.columns.length === 1 &&
      constraint.columns[0] === sqliteAuto.name
    ) {
      continue;
    }
    parts.push(`  ${constraintSql(constraint, constraintName(table.name, constraint, ++seq))}`);
  }
  return `create table ${quoteIdentifier(table.name)} (\n${parts.join(",\n")}\n)`;
}

/**
 * SQLite 的 AUTOINCREMENT 约束：只能是单列 `INTEGER PRIMARY KEY`。
 * 不满足时报错，而不是生成一条会被 SQLite 拒绝（或静默退化为普通 rowid）的建表语句。
 */
function sqliteAutoIncrementColumn(table: SchemaTable): Column | undefined {
  const autoColumns = table.columns.filter((c) => c.autoIncrement);
  if (autoColumns.length === 0) return undefined;
  if (autoColumns.length > 1) {
    throw diagnostic("ddl_1", table.name);
  }
  const column = autoColumns[0]!;
  if (column.type.toLowerCase() !== "integer") {
    throw diagnostic("ddl_2", table.name, column.name, column.type);
  }
  const primaryKey = table.constraints.find((c) => c.kind === "PRIMARY_KEY");
  if (
    primaryKey == null ||
    primaryKey.columns.length !== 1 ||
    primaryKey.columns[0] !== column.name
  ) {
    throw diagnostic("ddl_3", table.name, column.name);
  }
  return column;
}

/** 表级约束片段（inline 形态） */
export function constraintSql(constraint: Constraint, name: string): string {
  switch (constraint.kind) {
    case "PRIMARY_KEY":
      return `constraint ${quoteIdentifier(name)} primary key (${constraint.columns.map(quoteIdentifier).join(", ")})`;
    case "UNIQUE":
      return `constraint ${quoteIdentifier(name)} unique (${constraint.columns.map(quoteIdentifier).join(", ")})`;
    case "FOREIGN_KEY":
      return (
        `constraint ${quoteIdentifier(name)} foreign key (${constraint.columns.map(quoteIdentifier).join(", ")})` +
        ` references ${quoteIdentifier(constraint.referencedTable)} (${constraint.referencedColumns.map(quoteIdentifier).join(", ")})` +
        onDeleteSql(constraint.onDelete)
      );
    case "CHECK":
      return `constraint ${quoteIdentifier(name)} check (${constraint.expression})`;
  }
}

/** Independent index DDL for PostgreSQL and SQLite. */
export function indexSql(table: string, index: Index): string {
  return `create ${index.unique ? "unique " : ""}index ${quoteIdentifier(index.name)} on ${quoteIdentifier(table)} (${index.columns.map(quoteIdentifier).join(", ")})${index.predicate ? ` where ${index.predicate}` : ""}`;
}
